server {
    listen 3037;
    server_name gabarito.paiva.api.br;

    root /var/www/gabarito/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock; # Verifique sua versão do PHP
    }
}