# APP PROFESSOR - Ouvindo na porta que o Túnel espera
server {
    listen 3033;
    server_name qrcode.paiva.api.br;

    root /var/www/sistema-formacao/app-professor/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# APP ADMIN - Ouvindo na porta que o Túnel espera
server {
    listen 3034;
    server_name formar.paiva.api.br;

    root /var/www/sistema-formacao/app-admin/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}